### ISSUE TITLE
Installing `dbt-spark` without specifying a version forces update of `dbt-core`

### ISSUE THREAD

**Issue by DrMcTaco** [mwhitaker/dbt-action#11]
The `pip install` command in the [DOCKERFILE](https://github.com/mwhitaker/dbt-action/blob/master/Dockerfile#L6) to install the `dbt-spark` package cause an update of the `dbt-core` package. This makes the selection of a given base image version non-functional. 

The following are excerpts from the build of the container used in this action: 
```
Build container for action use: '/home/runner/work/_actions/mwhitaker/dbt-action/master/Dockerfile'.
  /usr/bin/docker build -t fa4e14:e38c1f6462d14f3cbf2d823e43d0ffdb -f "/home/runner/work/_actions/mwhitaker/dbt-action/master/Dockerfile" "/home/runner/work/_actions/mwhitaker/dbt-action/master"
  Sending build context to Docker daemon  16.38kB
  
  Step 1/6 : ARG DBT_VERSION=0.19.1
  Step 2/6 : FROM fishtownanalytics/dbt:${DBT_VERSION}
  0.19.1: Pulling from fishtownanalytics/dbt

...

  Successfully installed Jinja2-2.11.3 PyHive-0.6.4 dbt-core-0.21.0 dbt-extractor-0.4.0 dbt-spark-0.21.0 future-0.18.2 hologram-0.0.14 mashumaro-2.5 packaging-20.9 pure-sasl-0.6.2 pyparsing-2.4.7 sasl-0.3.1 sqlparams-3.0.0 thrift-0.11.0 thrift-sasl-0.4.3
  ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
  dbt 0.19.1 requires dbt-core==0.19.1, but you have dbt-core 0.21.0 which is incompatible.
  dbt-snowflake 0.19.1 requires dbt-core==0.19.1, but you have dbt-core 0.21.0 which is incompatible.
  dbt-redshift 0.19.1 requires dbt-core==0.19.1, but you have dbt-core 0.21.0 which is incompatible.
  dbt-postgres 0.19.1 requires dbt-core==0.19.1, but you have dbt-core 0.21.0 which is incompatible.
  dbt-bigquery 0.19.1 requires dbt-core==0.19.1, but you have dbt-core 0.21.0 which is incompatible.
...
```

I think this can be resolved by fixing the version of the additional dbt plugins installed to the same version specified by the `DBT_VERSION` argument

**Comment by mwhitaker** [comment]
Thank you for bringing this to my attention. I'm always a step behind when images are updated.

Could you please try your workflow again using:
```yml
- name: dbt-run
        id: dbt-run
        uses: mwhitaker/dbt-action@fishtown-v0.21.0
```
This works for me now and if does for you, I'll publish the update to the main branch.

Many thanks,
Michael

**Comment by DrMcTaco** [comment]
The new branch now does work, however I do not think this will fix the underlying issue of the Dockerfile specifying a given version and then pip updating the core packages to the latest release. If you pin the versions of `dbt-spark` and  `dbt-spark[PyHive]` to the same version in the `DBT_VERSION` arg these version specific branches will not need to be updated on each new release of dbt. 
I can provide a PR with that solution today.
