### ISSUE TITLE
Update for dbt v1.0.0

### ISSUE THREAD

**Issue by drernie** [mwhitaker/dbt-action#16]
This was released mid-December at Coalesce.
Can you release a new version? How should we specify that?

https://coalesce.getdbt.com/talks/dbt-v10-reveal/

**Comment by drernie** [comment]
FYI, I would also want to the (preview) dbt-databricks adapter

`
    Could not find adapter type databricks!
`

**Comment by mwhitaker** [comment]
Hi there,
I created a new branch for dbt v1.0.0 and the databricks adapter. Can you please try your workflow with:
```yaml
uses: mwhitaker/dbt-action@fishtown-v1.0
```
Once it looks good I can update the main branch.

Michael

**Comment by drernie** [comment]
Worked! Thanks for the fast turnaround :-)
