### ISSUE TITLE
Master - Isn't Building Docker Container

### ISSUE THREAD

**Issue by RyleeIacolucci** [mwhitaker/dbt-action#21]
Our team noticed that this wasn't working the same as it was before 2/25/2022. Here the error we're getting:

Need to get 456 kB of archives.
  After this operation, 925 kB of additional disk space will be used.
  Do you want to continue? [Y/n] Abort.
  The command '/bin/sh -c apt-get update && apt-get install libsasl2-dev' returned a non-zero code: 1
  Warning: Docker build failed with exit code 1, back off 1.525 seconds before retry.
  /usr/bin/docker build -t 7db2d7:bdc4fc3503c14580a6da3d090a4fbc21 -f "/home/runner/work/_actions/mwhitaker/dbt-action/master/Dockerfile" "/home/runner/work/_actions/mwhitaker/dbt-action/master"
  Sending build context to Docker daemon   16.9kB
  
  Step 1/7 : ARG DBT_VERSION=1.0.0
  Step 2/7 : FROM fishtownanalytics/dbt:${DBT_VERSION}
   ---> d874bacd7d19
  Step 3/7 : RUN apt-get update && apt-get install libsasl2-dev
   ---> Running in c8ebff6b580f
  Get:1 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
  Get:2 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [121 kB]
  Get:3 http://deb.debian.org/debian bullseye InRelease [116 kB]
  Get:4 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
  Get:5 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB]
  Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [25[96](https://github.com/PACCAR-PPD/ppd-de-it-materialized-tables-views/runs/5342321654?check_suite_focus=true#step:2:96) B]
  Fetched 8506 kB in 1s (6234 kB/s)
  Reading package lists...
  Reading package lists...
  Building dependency tree...
  Reading state information...
  The following additional packages will be installed:
    libsasl2-2 libsasl2-modules-db
  Recommended packages:
    libsasl2-modules
  The following NEW packages will be installed:
    libsasl2-dev
  The following packages will be upgraded:
    libsasl2-2 libsasl2-modules-db
  2 upgraded, 1 newly installed, 0 to remove and 14 not upgraded.
  Need to get 456 kB of archives.
  After this operation, 925 kB of additional disk space will be used.
  Do you want to continue? [Y/n] Abort.
  The command '/bin/sh -c apt-get update && apt-get install libsasl2-dev' returned a non-zero code: 1
  Warning: Docker build failed with exit code 1, back off 4.486 seconds before retry.
  /usr/bin/docker build -t 7db2d7:bdc4fc3503c14580a6da3d090a4fbc21 -f "/home/runner/work/_actions/mwhitaker/dbt-action/master/Dockerfile" "/home/runner/work/_actions/mwhitaker/dbt-action/master"
  Sending build context to Docker daemon   16.9kB
  
  Step 1/7 : ARG DBT_VERSION=1.0.0
  Step 2/7 : FROM fishtownanalytics/dbt:${DBT_VERSION}
   ---> d874bacd7d19
  Step 3/7 : RUN apt-get update && apt-get install libsasl2-dev
   ---> Running in a[97](https://github.com/PACCAR-PPD/ppd-de-it-materialized-tables-views/runs/5342321654?check_suite_focus=true#step:2:97)435e97b3e
  Get:1 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
  Get:2 http://deb.debian.org/debian bullseye InRelease [116 kB]
  Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
  Get:4 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [121 kB]
  Get:5 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB]
  Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [2596 B]
  Fetched 8506 kB in 1s (6614 kB/s)
  Reading package lists...
  Reading package lists...
  Building dependency tree...
  Reading state information...
  The following additional packages will be installed:
    libsasl2-2 libsasl2-modules-db
  Recommended packages:
    libsasl2-modules
  The following NEW packages will be installed:
    libsasl2-dev
  The following packages will be upgraded:
    libsasl2-2 libsasl2-modules-db
  2 upgraded, 1 newly installed, 0 to remove and 14 not upgraded.
  Need to get 456 kB of archives.
  After this operation, 925 kB of additional disk space will be used.
  Do you want to continue? [Y/n] Abort.
  The command '/bin/sh -c apt-get update && apt-get install libsasl2-dev' returned a non-zero code: 1
Error: Docker build failed with exit code 1

**Comment by ivanspog** [comment]
➕ Same issue on our side
