### ISSUE TITLE
Upgrade to newer version

### ISSUE THREAD

**Issue by Bada-S** [mwhitaker/dbt-action#24]
Hi, it would be awesome if newer versions of dbt(dbt-core) were supported. There have been some bug fixes in versions 1.0.1 in particular that I find very helpful

**Comment by mwhitaker** [comment]
Hi there,

This Github action uses Docker images published by the dbt team. The last one is v1.0.0, which is what my current version uses: https://hub.docker.com/r/fishtownanalytics/dbt/tags. Once there is a newer Docker image I'll update my code.

Thanks for letting me know!

Michael

**Comment by mwhitaker** [comment]
Thank you! Indeed, was not aware of this change. I'll take a look and work on updating this action.

**Comment by mwhitaker** [comment]
Could you please try your workflow run with:

```yml
  uses: mwhitaker/dbt-action@v1.0.4
```
The output from `dbt --version` looks like:
```
installed version: 1.0.4
   latest version: 1.0.4

Up to date!

Plugins:
  - postgres: 1.0.4 - Up to date!
  - redshift: 1.0.0 - Up to date!
  - spark: 1.0.0 - Up to date!
  - snowflake: 1.0.0 - Up to date!
  - bigquery: 1.0.0 - Up to date!
```
I built the image from [here](https://github.com/dbt-labs/dbt-core/blob/bumping-version/1.0.4_2001056751/docker/Dockerfile
).
