### ISSUE TITLE
Is there a way to use dbt actions with oath impersonate profile login 

### ISSUE THREAD

**Issue by sayaninja** [mwhitaker/dbt-action#25]
Is there a way to use dbt actions with impersonated service account?

https://docs.getdbt.com/reference/warehouse-profiles/bigquery-profile#service-account-impersonation

**Comment by mwhitaker** [comment]
Hi there,

Many thanks for the question, which I sadly overlooked until now.

I am familiar with service account impersonation through using **gcloud**, either locally or in a GCP environment. gcloud runs in the context of default application credentials and service account impersonation allows you to run code without having to download the keys of that impersonated service account. 

One way I can see that this would work with Github Actions is that the (self-hosted) runner has to be hosted in a GCP environment. If you use the Github-hosted runner, your workflow somehow needs to setup gcloud through https://github.com/google-github-actions/setup-gcloud, but this requires service account credentials to also be stored on Github?  So I am not sure what would be gained by service account impersonation if you could just store the service account credentials directly in Github secrets.

Anyway, I am just talking out loud. If you can let me know your workflow I can see if the action needs to be updated.

Michael
