### ISSUE TITLE
Use with https://github.com/Tomme/dbt-athena

### ISSUE THREAD

**Issue by andrewcstewart** [mwhitaker/dbt-action#41]
Any guidance on how one could use this with third party adaptors like `dbt-athena` ?  I take it that might require adding to the action's image build?

**Comment by mwhitaker** [comment]
Hi there,

Right now I am building the dbt image with all the dependencies as a separate step. I then upload that to [Docker hub](https://hub.docker.com/r/mwhitaker/dbt_all/tags). I guess we could try to add `dbt-athena` to the [Dockerfile](https://github.com/mwhitaker/dbt-action/blob/25e76ae2ad87799fb5e017e4579ef166bfc18701/Docker_build/Dockerfile#L110). Not sure if there are any downsides to adding third-party plugins to my generic image or if there should be different base images depending on the desired third-party plugin.
