### ISSUE TITLE
latest release pointing to a wrong dbt version

### ISSUE THREAD

**Issue by joelazar** [mwhitaker/dbt-action#43]
Unfortunately, the latest `v1.3.0` version points to a wrong commit. Screenshots -->
![image](https://user-images.githubusercontent.com/16268238/203075532-00a4f7f6-d476-4e70-8a0d-476d9b51f258.png)
![image](https://user-images.githubusercontent.com/16268238/203075539-1ac2a7d9-032c-4fef-919a-b61ee124292b.png)

**Comment by mwhitaker** [comment]
Thank you for that @joelazar - Redid the tags and should be good now!

**Comment by joelazar** [comment]
> Thank you for that @joelazar - Redid the tags and should be good now!

Thank you for the quick fix :pray:
