### ISSUE TITLE
`set-ouptut` warning

### ISSUE THREAD

**Issue by leo-schick** [mwhitaker/dbt-action#46]
Running the action returns a warning in the logs:

bq. Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

According to the blog item, set-output will throw an error starting 1st June 2023. This should be fixed latest some days in advance.

I gues its just these two code lines which needs to be changed:
* [/entrypoint.sh#L43](https://github.com/mwhitaker/dbt-action/blob/25e76ae2ad87799fb5e017e4579ef166bfc18701/entrypoint.sh#L43)
* [/entrypoint.sh#L47](https://github.com/mwhitaker/dbt-action/blob/25e76ae2ad87799fb5e017e4579ef166bfc18701/entrypoint.sh#L47)

**Comment by mestesarch** [comment]
Hi @mwhitaker. even with v1.3.0, I still get warnings about set-output commands being present. It causes some issues in our workflows. Thoughts?

**Comment by spaquettepare** [comment]
Hi @mwhitaker, just a reminder that GitHub is set to deprecate the `set-output` on may 31! Which is in about 50 days.
