### ISSUE TITLE
dbt version upgrade 1.6.1

### ISSUE THREAD

**Issue by leo-schick** [mwhitaker/dbt-action#56]
I would like to use dbt version 1.6.1

**Comment by mwhitaker** [comment]
I updated this to v1.6.3

Would you mind testing this out with
```
uses: mwhitaker/dbt-action@v1.6.3
```
before I set the main branch to this version?

**Comment by leo-schick** [comment]
@mwhitaker Yes, it works in production for me. Thanks!
