### ISSUE TITLE
Switch to dbt Hosted Docker Images

### ISSUE THREAD

**Issue by christopher-leigh** [mwhitaker/dbt-action#57]
Instead of building Docker Images and manually / hosting on Docker Hub, couldn't we change update this project to reference dbt's hosted images on GitHub? See [here](https://github.com/dbt-labs/dbt-core/pkgs/container/dbt-core).

**Comment by mwhitaker** [comment]
Yeah that would be cool. I am sure these built images weren't around when I worked on this Github Action a long time ago, hence me going down that rabbit hold to build them myself. Thanks for the heads up!

**Comment by christopher-leigh** [comment]
Yes that makes a ton of sense! I know they are constantly making updates so things change quickly in this realm. Appreciate all of your work on this, this really helped our team get dbt up and running quickly 🙂

I created a PR from my work GitHub account that pulls from their Snowflake image (because that's what we use) as an example just FYI!
